'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{createRequire}=require('node:module'),{EventEmitter}=require('node:events');const root=path.resolve(__dirname,'../..');
(async()=>{
 const reads=[];const pc={module:{exports:{}},process:{env:{BCH_INDEXER:'https://indexer.test'}},URL,Map,Math,Number,Date,AbortSignal,setTimeout,fetch:async url=>{reads.push(url);return {ok:true,status:200,json:async()=>new URL(url).searchParams.get('txids').split(',').map(txid=>({txid,fee:100,size:200,outputs:[{value:2000}],time:1700000000,block:txid==='confirmed'?{height:1}:{mempool:1700000000}}))}}};vm.runInNewContext(fs.readFileSync(root+'/adapter/bch-provider.cjs','utf8'),pc);const mapped=pc.module.exports.transaction({txid:'pending',block:{mempool:1700000000},inputs:[],outputs:[],size:200,fee:100});assert.equal(mapped.status.confirmed,false);assert.equal(mapped.firstSeen,1700000000);const ids=Array.from({length:110},(_,i)=>String(i));assert.equal((await pc.module.exports.pendingTiles(ids)).length,100);assert.equal(reads.length,5);await pc.module.exports.pendingTiles(ids);assert.equal(reads.length,5);const changed=await pc.module.exports.pendingTiles(['new','confirmed']);assert.equal(changed.length,1);assert.equal(changed[0][0],'new');assert.equal(reads.length,6);assert(reads.every(u=>new URL(u).searchParams.get('txids').split(',').length<=20));
 const nativeRequire=createRequire(root+'/adapter/server.cjs');let calls=0,round=0;const memberships=[['a','b'],['b','c'],[]];const fakeProvider={snapshot:async()=>{calls++;await new Promise(r=>setTimeout(r,10));return {blocks:[{height:1}],mempoolInfo:{size:memberships[round].length},'projected-block-transactions':{index:0,sequence:round+1,blockTransactions:memberships[round].map(id=>[id,100,200,2000,0.5,0,1700000000])}}},record:()=>{},api:async()=>{throw Object.assign(Error('Unsupported capability'),{status:501})}};
 const sc={module:{exports:{}},require:p=>p==='./bch-provider.cjs'?fakeProvider:nativeRequire(p),__dirname:root+'/adapter',process:{env:{}},console,URL,Buffer,Date,setInterval:()=>0,setTimeout,Response,AbortSignal};let source=fs.readFileSync(root+'/adapter/server.cjs','utf8').replace('setInterval(refresh,15000);refresh();','');source=source.slice(0,source.lastIndexOf('server.listen'))+'\nmodule.exports={refresh,api,wss,health,failedPaths};';vm.runInNewContext(source,sc);const server=sc.module.exports;
 class Client extends EventEmitter{constructor(){super();this.readyState=1;this.frames=[];}send(raw){this.frames.push(JSON.parse(raw));}close(){}}
 const clients=Array.from({length:8},()=>new Client());for(const c of clients){server.wss.clients.add(c);server.wss.emit('connection',c)}await Promise.all(Array.from({length:8},()=>server.refresh()));assert.equal(calls,1,'concurrent init/refresh must share collector');for(const c of clients)c.emit('message',JSON.stringify({'track-mempool-block':0}));await new Promise(r=>setTimeout(r,20));assert.equal(calls,1,'subscription must reuse cached tiles');round=1;await server.refresh();for(const c of clients)assert.equal(JSON.stringify(c.frames.at(-1)['projected-block-transactions'].blockTransactions.map(t=>t[0])),JSON.stringify(['b','c']));round=2;await server.refresh();for(const c of clients)assert.equal(c.frames.at(-1)['projected-block-transactions'].blockTransactions.length,0);const unsupported=await server.api('/api/v1/mining/pool/unknown/blocks');assert.equal(unsupported.status,501);assert.equal(unsupported.data.retryable,false);assert.equal(server.failedPaths.size,0);assert.equal(server.health.lastFailure,null);
 const result={clients:8,collectorCalls:calls,framesPerClient:clients.map(c=>c.frames.length),membership:memberships,maxSample:100,maxBatch:20,indexerRequests:reads.length,unknownPoolStatus:unsupported.status,globalFailures:server.failedPaths.size};fs.writeFileSync(__dirname+'/controlled.json',JSON.stringify(result,null,2));console.log(result);server.wss.close();
})().catch(e=>{console.error(e);process.exitCode=1});
