import {chromium} from '/home/lukee/.local/share/pnpm/global/5/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
const chain=process.argv[2],origin=process.argv[3],stage=process.argv[4]||'local';
const dir='/home/lukee/dev/ltc-taxi/review/deployment/palette-consistency';fs.mkdirSync(dir,{recursive:true});
const b=await chromium.launch({executablePath:'/home/lukee/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--enable-unsafe-swiftshader']});const reports=[];
try{for(const [size,viewport] of [['desktop',{width:1440,height:900}],['mobile',{width:390,height:844}]]){
 const p=await b.newPage({viewport});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(origin);await p.locator('.fee-text:visible').first().waitFor({timeout:45000});await p.waitForTimeout(2200);
 const read=()=>p.evaluate(()=>{const css=getComputedStyle(document.documentElement);const visible=s=>[...document.querySelectorAll(s)].find(e=>e.getBoundingClientRect().width>0);return {primary:css.getPropertyValue('--primary').trim(),alt:css.getPropertyValue('--mainnet-alt').trim(),panel:css.getPropertyValue('--stat-box-bg').trim(),fee:visible('.fee-progress-bar')&&getComputedStyle(visible('.fee-progress-bar')).background,feeText:visible('.fee-progress-bar')&&getComputedStyle(visible('.fee-progress-bar')).color,blocks:[...document.querySelectorAll('.progress-mempool')].slice(0,4).map(e=>getComputedStyle(e).backgroundImage),overflow:document.documentElement.scrollWidth>innerWidth};});
 const native=await read();assert.notEqual(native.alt,'#9339f4');assert.equal(native.overflow,false);
 const hue= native.fee.match(/rgb\((\d+), (\d+), (\d+)\)/);assert.ok(hue,'Rendered fee ramp');if(['eth','ltc'].includes(chain))assert.ok(+hue[3]>+hue[1]);else assert.ok(+hue[1]>+hue[2]&&+hue[2]>+hue[3]);
 await p.screenshot({path:`${dir}/${chain}-${stage}-${size}-root.png`});
 let links=await p.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));let tx=links.find(x=>/^\/tx\/(0x)?[a-f0-9]{64}$/.test(x));let block=links.find(x=>/^\/block\/(0x)?[a-f0-9]{64}$/.test(x));
 if(block){const id=block.split('/').at(-1);const r=await p.request.get(origin+'/api/block/'+id+'/txids');if(r.ok()){const ids=await r.json();if(ids[1])tx='/tx/'+ids[1];}}
 if(!tx){const r=await p.request.get(origin+'/api/mempool/recent');if(r.ok()){const xs=await r.json();tx='/tx/'+xs[0]?.txid;}}
 assert.ok(tx&&!tx.endsWith('undefined'),'Representative transaction available');
 await p.locator('app-theme-selector select:visible').first().selectOption('original');await p.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--mainnet-alt').trim()==='#9339f4');await p.waitForTimeout(500);const original=await read();assert.notEqual(original.fee,native.fee);await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:`${dir}/${chain}-${stage}-${size}-original.png`});
 await p.locator('app-theme-selector select:visible').first().selectOption('default');await p.reload();await p.locator('.fee-text:visible').first().waitFor({timeout:45000});assert.equal((await read()).alt,native.alt);
 await p.goto(origin+tx);await p.waitForTimeout(4000);const details=p.getByText('See more details',{exact:false});const feeLabel=p.locator('app-transaction-details td').filter({hasText:/^(Fee|Maximum fee)$/}).first();await feeLabel.or(details).first().waitFor({timeout:45000});if(await details.isVisible())await details.click();await feeLabel.waitFor({timeout:45000});const show=p.getByRole('button',{name:'Show diagram',exact:true});if(await show.isVisible())await show.click();const graph=p.locator('tx-bowtie-graph');if(await graph.isVisible())await graph.scrollIntoViewIfNeeded();await p.screenshot({path:`${dir}/${chain}-${stage}-${size}-tx.png`});assert.equal(await p.getByText('Transaction not found',{exact:false}).count(),0);
 const flow=await p.locator('#input-gradient stop').first().evaluate(e=>getComputedStyle(e).stopColor).catch(()=>null);if(flow)assert.notEqual(flow,'rgb(147, 57, 244)');
 if(block){await p.goto(origin+block);await p.waitForTimeout(3000);await p.screenshot({path:`${dir}/${chain}-${stage}-${size}-block.png`});}
 assert.deepEqual(errors,[]);reports.push({size,native,originalFee:original.fee,themeRoundTrip:true,tx,block,flow,errors});await p.close();
}fs.writeFileSync(`${dir}/${chain}-${stage}.json`,JSON.stringify({at:new Date().toISOString(),origin,reports},null,2));console.log(chain,stage,'PASS',reports.map(r=>({size:r.size,tx:r.tx,flow:r.flow})));}catch(e){const p=b.contexts().at(-1)?.pages().at(-1);if(p){console.log(p.url(),(await p.locator('body').innerText()).slice(-2500));await p.screenshot({path:`${dir}/${chain}-${stage}-failure.png`});}throw e;}finally{await b.close();}
